export const chapters = {
  "1": {
    title: "Тень в бамбуке",
    pages: [
      { page: 1, scene: "Wide: hidden shadow blade village in misty bamboo at dawn, purple lanterns, training yard.", narration: ["Деревня теневых клинков прячется в бамбуке. Утро пахнет влажной соломой и сталью."], dialogue: [{ speaker: "shima", text: "Три лезвия — один выдох. Сегодня без скидок, Мия." }, { speaker: "miya", text: "Вдох короткий. Лезвия длиннее." }], sfx: null },
      { page: 2, scene: "Training yard: Miya throws shuriken fan, three blades spread ±15 degrees toward wooden targets.", narration: ["Двор учит не попадать. Двор учит не давать врагу дышать."], dialogue: [{ speaker: "shima", text: "Центральный — в сердце мишени. Боковые — в углы бегства." }, { speaker: "kaito", text: "Она снова бьёт все три. Как будто бамбук сам подставляет шею." }, { speaker: "miya", text: "Бамбук молчит. Я — нет." }], sfx: null },
      { page: 3, scene: "Hairline purple reality crack flickers above village gate — first omen.", narration: ["Над воротами воздух ломается тонкой трещиной. Не гром — разрыв."], dialogue: [{ speaker: "kaito", text: "Сима-сэнсэй! Небо рвётся, как старый свиток!" }, { speaker: "miya", text: "Трещина дышит. Не кричи — слушай." }], sfx: "ТРЕСК!" },
      { page: 4, scene: "Training hall: Miya teleports short distance behind wooden dummy, strikes with elbow.", narration: ["Секрет клана: шаг сквозь тень. Удар — туда, где враг ещё не повернул голову."], dialogue: [{ speaker: "shima", text: "Телепорт — не побег. Это нож в спину сомнению." }, { speaker: "miya", text: "Стань за мной, Кайто. Увидишь, как тень кусает." }, { speaker: "kaito", text: "Ты… исчезла и снова здесь. Это нечестно." }], sfx: "WHOOSH!" },
      { page: 5, scene: "Perfect triple shuriken hit on three targets simultaneously, splinters fly.", narration: ["Три мишени. Три вспышки стали. Один бросок."], dialogue: [{ speaker: "shima", text: "Чисто. Клан ещё дышит через твои запястья." }, { speaker: "miya", text: "Пока лезвия летят — дом стоит." }, { speaker: "kaito", text: "Счастливая. Ещё и хвастается тишиной." }], sfx: "ВЖУХ!" },
      { page: 6, scene: "Night: Miya reads Ren's letter by candlelight, red ribbon on desk, brother alive in words.", narration: ["Письмо брата пахнет дорожной пылью и чужим песком. Рэн жив — пока чернила не высохли."], dialogue: [{ speaker: "ren", text: "Сестра, я на пороге Арены. Жетон горячий, как лихорадка." }, { speaker: "miya", text: "Вернись до того, как письмо станет прощанием." }, { speaker: "ren", text: "Обещаю шагнуть на песок и оглянуться на бамбук." }], sfx: null },
      { page: 7, scene: "Through bamboo gaps, distant Arena dome glows purple on horizon at dusk.", narration: ["Купол Арены проступает сквозь стебли — далёкий костёр для тех, кто ищет имя убийцы."], dialogue: [{ speaker: "kaito", text: "Рэн писал, что слышит толпу сквозь ветер." }, { speaker: "miya", text: "Ветер врёт редко. Люди — чаще." }, { speaker: "shima", text: "Не беги за эхом, пока не научишься резать собственный страх." }], sfx: null },
      { page: 8, scene: "Miya at village gate, three shurikens ready, purple tear energy gathers at fingertips.", narration: ["Выбор стоит у ворот: остаться тенью деревни — или выйти на след маски с сакурой."], dialogue: [{ speaker: "shima", text: "За воротами клан не держит тебя за пояс." }, { speaker: "miya", text: "Клан держит клятву. Я проложу тропу сама." }, { speaker: "kaito", text: "Ты уйдёшь — и снова вернёшься первой. Всегда так." }], sfx: null },
      { page: 9, scene: "Training ring: reality tear opens briefly, shuriken storm inside purple rift.", narration: ["Разрыв реальности зевает на мгновение. Сюрикены летят сквозь трещину, как град из стали."], dialogue: [{ speaker: "kaito", text: "Она бросила лезвия в разлом!" }, { speaker: "shima", text: "Вижу силу. Боюсь, что без деревни она станет только лезвием." }, { speaker: "miya", text: "Лезвие без цели — просто металл. У меня есть имя: Рэн." }], sfx: "KRAK-BOOM!" },
      { page: 10, scene: "Cliffhanger: largest shuriken emblem on gate cracks, Miya watches purple light leak.", narration: ["Глава I. Тень в бамбуке. Эмблема клана треснула — мир ещё не знает, чей след придёт следующим."], dialogue: [{ speaker: "miya", text: "Если правда за горизонтом — я дойду, даже ценой собственной тени." }, { speaker: "shima", text: "Тень без дома гниёт. Запомни." }], sfx: "ШШШШ!" }
    ]
  },
  "2": {
    title: "Пепел клана",
    pages: [
      { page: 1, scene: "Burned ruins of shadow blade village at night, smoke, collapsed bamboo, embers.", narration: ["Ночь после налёта. Клан Хакурэна оставил только пепел и тишину, которая режет уши."], dialogue: [{ speaker: "miya", text: "Я опоздала на один вдох. Одного вдоха хватило, чтобы убить дом." }, { speaker: "renSpirit", text: "Ты пришла — значит, клятва ещё не рассыпалась." }], sfx: null },
      { page: 2, scene: "Close-up: Ren's final letter stained with blood, Miya's purple eyes reflect embers.", narration: ["Второе письмо. Чернила смешались с кровью. Рэн мёртв — слово стало пеплом."], dialogue: [{ speaker: "ren", text: "…если читаешь это — маска с сакурой уже здесь. Не мсти вслепую." }, { speaker: "miya", text: "Слепая месть — твоя просьба. Моя — найти имя на маске." }], sfx: null },
      { page: 3, scene: "White-masked hunters with sakura marks walk through rubble, torches, nets ready.", narration: ["Безликие в белых масках. На одной — цветок сакуры. Они не оставляют свидетелей."], dialogue: [{ speaker: "facelessCaptain", text: "Последняя тень клана. Отдай жетон брата." }, { speaker: "miya", text: "Жетон — на моём сердце. Забирай, если догонишь мой шаг." }], sfx: "РРРАЗЛОМ!" },
      { page: 4, scene: "Chase through burning bamboo, hunters throw weighted nets from shadows.", narration: ["Погоня в дыму. Сети падают, как приговор. Мия режет воздух, не небо."], dialogue: [{ speaker: "facelessCaptain", text: "Беги по пеплу. Устанешь — и мы вырвем твоё имя." }, { speaker: "miya", text: "Имя моё — Мия. Запиши, пока дышишь." }], sfx: "WHOOSH!" },
      { page: 5, scene: "Miya throws triple shuriken, pins hunter's cloak to charred wall.", narration: ["Первый ответ боли — три лезвия быстрее слёз и быстрее оправданий."], dialogue: [{ speaker: "miya", text: "Твой след ведёт к Рэну. Я читаю грязь, как свиток." }, { speaker: "facelessHunter", text: "Девчонка… режет плащ точнее мастера!" }], sfx: "ВЖУХ!" },
      { page: 6, scene: "Miya kneels by fallen clan banner, Ren's katana broken in ash, red ribbon tied to hilt.", narration: ["Знамя клана под сапогами. Красная лента на сломанной катане — последний дар брата."], dialogue: [{ speaker: "renSpirit", text: "Мы держали двор, пока верили в справедливость, а не в крик." }, { speaker: "miya", text: "Я верю. Поэтому стою на пепле, а не бегу от него." }], sfx: null },
      { page: 7, scene: "Arena dome pulses through smoke on horizon, purple light on burned torii.", narration: ["Купол проступает сквозь дым — маяк для тех, кто ищет маску с сакурой."], dialogue: [{ speaker: "miya", text: "Рэн ушёл туда. Значит, и я — на его след." }, { speaker: "kaito", text: "Ты одна? Я… я тоже потерял дом." }, { speaker: "miya", text: "Тогда не путай страх с пустотой. Иди или стой — но не мешай." }], sfx: null },
      { page: 8, scene: "Miya loads three shurikens, purple tear energy coils along steel edges.", narration: ["Последний запас деревни. Каждый бросок — вычтенный вдох покоя."], dialogue: [{ speaker: "miya", text: "Каждый сюрикен — обещание Рэну назвать убийцу." }, { speaker: "shima", text: "Обещание тяжелее стали. Не роняй." }], sfx: null },
      { page: 9, scene: "Burning dojo collapses, Miya teleports out in purple flash between falling beams.", narration: ["Додзё рушится. Телепорт — единственная стена между ней и могилой из балок."], dialogue: [{ speaker: "facelessCaptain", text: "Невозможно… она выскользнула из обвала!" }, { speaker: "miya", text: "Невозможное — то, чему меня учили до пепла." }], sfx: "KRAK-BOOM!" },
      { page: 10, scene: "Lone figure on last standing torii gate, shuriken emblem cracked above.", narration: ["Глава II. Пепел клана. На воротах осталась одна тень — и клятва без дома."], dialogue: [{ speaker: "miya", text: "Я последний клинок деревни. Значит — я и есть его стена." }, { speaker: "renSpirit", text: "Стена не мстит. Стена даёт выбор тем, кто за ней." }], sfx: "ВДЫХ." }
    ]
  }
};
