import {
  T, CX, CY, LEFT, TOP, BOT,
  bushGrove, cornerFort, crossArena, openRing, waterL, diagonalStairs,
  leftLaneWall, leftPerimeterBushes, sandBarrier, fenceRow,
  lanePair, openCenter, coverAlcove, deco, heal,
  BUSH_RING3, BUSH_PLUS, BUSH_BLOCK, BUSH_LINE, distributedScatter,
} from "./helpers.mjs";

const perim = (mode) => leftPerimeterBushes(2)(mode);

export const MODE_DESIGNS = {
  showdown: [
    () => openCenter([
      ...perim("showdown"),
      ...openRing(CX - 8, CY - 8, 5, T.WALL),
      ...cornerFort(LEFT + 5, TOP + 5, 0),
      ...cornerFort(CX - 5, CY - 5, 2),
      ...bushGrove(LEFT + 10, TOP + 10, BUSH_RING3),
      ...bushGrove(CX - 12, TOP + 8, BUSH_BLOCK),
      ...lanePair(TOP + 12, CY - 6, 12),
      ...fenceRow(LEFT + 12, TOP + 20, 10),
      ...sandBarrier(LEFT + 8, TOP + 22, 8),
      deco(LEFT + 7, TOP + 7),
    ]),
    () => openCenter([
      ...perim("showdown"),
      ...crossArena(2, 5),
      ...cornerFort(LEFT + 4, TOP + 4, 0),
      ...cornerFort(LEFT + 4, CY - 4, 2),
      ...bushGrove(CX - 10, TOP + 12, BUSH_PLUS),
      ...bushGrove(LEFT + 16, TOP + 18, BUSH_LINE),
      ...leftLaneWall(TOP + 10, 14),
      ...leftLaneWall(CY - 2, 12),
      ...waterL(LEFT + 14, TOP + 8, 5, 4),
      heal(CX - 8, TOP + 10),
    ]),
    () => openCenter([
      ...perim("showdown"),
      ...diagonalStairs(LEFT + 7, TOP + 7, 8),
      ...sandBarrier(LEFT + 10, TOP + 20, 10),
      ...sandBarrier(CX - 10, TOP + 12, 8, true),
      ...bushGrove(LEFT + 18, TOP + 14, BUSH_BLOCK),
      ...bushGrove(CX - 6, CY - 8, BUSH_RING3),
      ...coverAlcove(LEFT + 12, TOP + 16, 4, 4, T.SAND_WALL, 0),
      ...fenceRow(LEFT + 8, CY - 4, 8),
      ...cornerFort(CX - 6, TOP + 6, 1),
    ]),
    () => openCenter([
      ...perim("showdown"),
      ...fenceRow(LEFT + 8, TOP + 10, 12),
      ...fenceRow(LEFT + 8, TOP + 18, 12),
      ...fenceRow(LEFT + 16, TOP + 8, 10, true),
      ...bushGrove(LEFT + 11, TOP + 14, BUSH_PLUS),
      ...bushGrove(CX - 8, TOP + 10, BUSH_BLOCK),
      ...coverAlcove(LEFT + 10, CY - 5, 5, 4, T.WALL, 2),
      ...leftLaneWall(TOP + 22, 10),
      ...waterL(CX - 9, TOP + 14, 4, 3),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
    ]),
    () => openCenter([
      ...perim("showdown"),
      ...lanePair(TOP + 8, TOP + 20, 16),
      ...lanePair(CY - 10, CY - 2, 12),
      ...coverAlcove(LEFT + 8, TOP + 12, 5, 4, T.WALL, 1),
      ...coverAlcove(CX - 10, TOP + 10, 4, 5, T.FENCE, 3),
      ...bushGrove(LEFT + 20, TOP + 8, BUSH_RING3),
      ...bushGrove(CX - 4, CY - 6, BUSH_PLUS),
      { kind: "waterRect", x: LEFT + 12, y: TOP + 22, w: 5, h: 3 },
      ...sandBarrier(CX - 11, TOP + 18, 7),
      deco(CX - 7, TOP + 8),
    ]),
  ],
  gemgrab: [
    () => [
      ...perim("gemgrab"),
      ...crossArena(2, 4),
      ...lanePair(CY - 8, CY + 8, 12),
      ...bushGrove(LEFT + 10, TOP + 10, BUSH_RING3),
      ...bushGrove(LEFT + 10, BOT - 10, BUSH_RING3),
      ...coverAlcove(CX - 10, TOP + 10, 5, 4, T.WALL, 2),
      ...cornerFort(LEFT + 8, TOP + 8, 0),
      ...cornerFort(LEFT + 8, BOT - 8, 2),
      ...fenceRow(LEFT + 14, CY, 8),
      ...waterL(LEFT + 16, TOP + 14, 4, 4),
    ],
    () => [
      ...perim("gemgrab"),
      ...openRing(CX - 6, CY, 4, T.FENCE),
      ...leftLaneWall(CY - 6, 12),
      ...leftLaneWall(CY + 6, 12),
      ...bushGrove(LEFT + 12, CY, BUSH_LINE),
      ...bushGrove(CX - 8, TOP + 12, BUSH_PLUS),
      ...coverAlcove(LEFT + 10, TOP + 12, 4, 5, T.WALL, 0),
      ...sandBarrier(CX - 8, BOT - 14, 8),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
      deco(LEFT + 14, CY),
    ],
    () => [
      ...perim("gemgrab"),
      ...diagonalStairs(LEFT + 8, TOP + 10, 7),
      ...diagonalStairs(LEFT + 8, BOT - 17, 7),
      ...bushGrove(LEFT + 16, CY, BUSH_BLOCK),
      ...lanePair(TOP + 12, BOT - 12, 10),
      ...coverAlcove(CX - 8, CY - 8, 5, 5, T.SAND_WALL, 1),
      ...fenceRow(LEFT + 8, TOP + 18, 10),
      { kind: "waterRect", x: LEFT + 14, y: TOP + 12, w: 4, h: 3 },
      ...cornerFort(CX - 6, BOT - 8, 2),
    ],
    () => [
      ...perim("gemgrab"),
      ...crossArena(3, 3, T.SAND_WALL),
      ...leftLaneWall(CY, 14),
      ...bushGrove(LEFT + 10, TOP + 14, BUSH_PLUS),
      ...bushGrove(LEFT + 10, BOT - 14, BUSH_PLUS),
      ...coverAlcove(LEFT + 12, CY - 4, 5, 9, T.FENCE, 2),
      ...coverAlcove(CX - 8, TOP + 10, 4, 4, T.WALL, 0),
      ...waterL(LEFT + 14, BOT - 14, 5, 4),
      ...sandBarrier(CX - 6, TOP + 8, 6),
      heal(LEFT + 18, TOP + 10),
    ],
    () => [
      ...perim("gemgrab"),
      ...fenceRow(LEFT + 8, TOP + 12, 12),
      ...fenceRow(LEFT + 8, BOT - 12, 12),
      ...fenceRow(CX - 8, TOP + 10, 12, true),
      ...bushGrove(CX - 4, TOP + 10, BUSH_BLOCK),
      ...bushGrove(CX - 4, BOT - 10, BUSH_BLOCK),
      ...lanePair(CY - 5, CY + 5, 14),
      ...coverAlcove(LEFT + 10, CY - 3, 6, 7, T.WALL, 2),
      { kind: "waterRect", x: CX - 5, y: CY - 1, w: 3, h: 3 },
      ...cornerFort(LEFT + 6, TOP + 8, 0),
    ],
  ],
  heist: [
    () => [
      ...lanePair(CY - 5, CY + 5, 12),
      ...bushGrove(CX - 4, CY - 3, BUSH_PLUS),
      ...coverAlcove(LEFT + 10, TOP + 10, 5, 4, T.WALL, 0),
      ...coverAlcove(LEFT + 10, BOT - 14, 5, 4, T.WALL, 1),
      ...fenceRow(LEFT + 14, CY, 8),
      ...cornerFort(LEFT + 8, BOT - 10, 2),
      ...waterL(LEFT + 12, TOP + 16, 4, 3),
      ...sandBarrier(CX - 8, TOP + 12, 6),
    ],
    () => [
      ...leftLaneWall(CY - 8, 14),
      ...leftLaneWall(CY + 8, 14),
      ...bushGrove(CX - 6, TOP + 12, BUSH_RING3),
      ...coverAlcove(LEFT + 8, TOP + 8, 6, 5, T.FENCE, 2),
      ...coverAlcove(CX - 8, BOT - 12, 5, 4, T.WALL, 0),
      ...cornerFort(CX - 6, BOT - 8, 2),
      ...fenceRow(LEFT + 16, TOP + 8, 6),
      ...waterL(LEFT + 14, CY + 6, 5, 4),
      deco(LEFT + 10, CY),
    ],
    () => [
      ...leftLaneWall(CY, 16),
      ...bushGrove(CX - 4, CY - 3, BUSH_BLOCK),
      ...coverAlcove(LEFT + 8, TOP + 8, 6, 6, T.WALL, 0),
      ...crossArena(2, 3),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
      ...sandBarrier(CX - 6, TOP + 14, 8),
      ...fenceRow(LEFT + 10, BOT - 12, 10),
      ...waterL(LEFT + 16, TOP + 10, 4, 4),
      heal(LEFT + 14, TOP + 16),
    ],
    () => [
      ...cornerFort(LEFT + 10, TOP + 10, 0),
      ...leftLaneWall(CY - 8, 12),
      ...coverAlcove(CX - 8, CY - 5, 7, 11, T.WALL, 2),
      ...bushGrove(LEFT + 16, CY, BUSH_PLUS),
      ...fenceRow(CX - 6, CY + 6, 7),
      ...waterL(LEFT + 12, TOP + 14, 4, 3),
      ...sandBarrier(LEFT + 8, BOT - 14, 8),
      ...diagonalStairs(LEFT + 10, BOT - 14, 5),
    ],
    () => [
      ...fenceRow(LEFT + 8, TOP + 12, 10),
      ...fenceRow(LEFT + 8, BOT - 12, 10),
      ...bushGrove(CX - 4, CY, BUSH_RING3),
      ...leftLaneWall(CY, 12),
      ...coverAlcove(LEFT + 12, CY - 4, 5, 9, T.WALL, 2),
      ...waterL(LEFT + 16, TOP + 10, 4, 4),
      ...cornerFort(LEFT + 6, BOT - 8, 2),
      ...sandBarrier(CX - 8, TOP + 10, 6),
      deco(CX - 8, CY + 6),
    ],
  ],
  bounty: [
    () => [
      ...openRing(CX - 6, CY, 4, T.WALL),
      ...bushGrove(LEFT + 10, TOP + 10, BUSH_PLUS),
      ...leftLaneWall(CY - 6, 10),
      ...leftLaneWall(CY + 6, 10),
      ...coverAlcove(LEFT + 12, CY - 3, 5, 7, T.WALL, 2),
      ...fenceRow(CX - 6, TOP + 8, 6),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
      ...waterL(LEFT + 14, CY + 4, 4, 3),
    ],
    () => [
      ...crossArena(2, 4),
      ...bushGrove(CX - 7, CY - 7, BUSH_BLOCK),
      ...leftLaneWall(CY - 5, 10),
      ...leftLaneWall(CY + 5, 10),
      ...coverAlcove(LEFT + 8, TOP + 10, 5, 5, T.FENCE, 0),
      ...sandBarrier(CX - 8, CY, 5),
      ...cornerFort(CX - 6, TOP + 8, 2),
      ...waterL(LEFT + 12, BOT - 12, 4, 4),
    ],
    () => [
      { kind: "waterRect", x: CX - 3, y: CY - 1, w: 7, h: 3 },
      { kind: "waterRect", x: CX - 1, y: CY - 3, w: 3, h: 7 },
      ...bushGrove(LEFT + 12, CY, BUSH_RING3),
      ...leftLaneWall(CY - 8, 8),
      ...leftLaneWall(CY + 8, 8),
      ...coverAlcove(LEFT + 10, TOP + 8, 5, 5, T.WALL, 1),
      ...cornerFort(CX - 6, BOT - 8, 2),
      ...fenceRow(LEFT + 8, TOP + 16, 10),
    ],
    () => [
      ...diagonalStairs(LEFT + 10, TOP + 8, 6),
      ...bushGrove(LEFT + 16, TOP + 14, BUSH_PLUS),
      ...leftLaneWall(CY - 5, 10),
      ...leftLaneWall(CY + 5, 10),
      ...coverAlcove(CX - 6, TOP + 10, 5, 5, T.WALL, 3),
      ...waterL(LEFT + 12, BOT - 12, 4, 4),
      ...sandBarrier(LEFT + 8, TOP + 18, 8),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
    ],
    () => [
      ...lanePair(CY - 5, CY + 5, 12),
      ...bushGrove(CX - 4, TOP + 10, BUSH_BLOCK),
      ...coverAlcove(LEFT + 10, CY - 4, 6, 9, T.WALL, 2),
      ...fenceRow(CX - 6, CY - 8, 7),
      ...cornerFort(LEFT + 8, TOP + 8, 0),
      ...openRing(LEFT + 18, TOP + 14, 3, T.FENCE),
      deco(LEFT + 14, CY),
      heal(CX - 8, TOP + 12),
    ],
  ],
  starstrike: [
    () => [
      ...coverAlcove(LEFT + 4, CY - 6, 8, 13, T.WALL, 2),
      ...bushGrove(CX - 6, CY, BUSH_RING3),
      ...leftLaneWall(CY - 5, 10),
      ...leftLaneWall(CY + 5, 10),
      ...fenceRow(LEFT + 12, TOP + 12, 8),
      ...cornerFort(LEFT + 6, BOT - 8, 2),
      ...sandBarrier(CX - 8, CY, 6),
    ],
    () => [
      ...lanePair(CY - 4, CY + 4, 10),
      ...bushGrove(LEFT + 12, CY, BUSH_PLUS),
      ...coverAlcove(CX - 6, TOP + 10, 5, 5, T.WALL, 0),
      ...waterL(LEFT + 14, CY + 4, 4, 3),
      ...leftLaneWall(TOP + 12, 8),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
      ...fenceRow(LEFT + 8, BOT - 10, 10),
    ],
    () => [
      ...crossArena(2, 3),
      ...bushGrove(LEFT + 10, TOP + 12, BUSH_BLOCK),
      ...leftLaneWall(CY, 10),
      ...coverAlcove(LEFT + 8, CY - 4, 6, 9, T.FENCE, 2),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
      ...sandBarrier(CX - 8, BOT - 12, 6),
    ],
    () => [
      ...bushGrove(CX - 8, CY, BUSH_RING3),
      ...leftLaneWall(CY - 6, 10),
      ...leftLaneWall(CY + 6, 10),
      ...coverAlcove(LEFT + 10, TOP + 10, 5, 5, T.WALL, 1),
      ...waterL(LEFT + 16, BOT - 14, 4, 3),
      ...fenceRow(CX - 6, TOP + 12, 6),
      deco(CX - 6, TOP + 8),
      ...cornerFort(CX - 6, BOT - 8, 2),
    ],
    () => [
      ...cornerFort(LEFT + 6, CY - 8, 0),
      ...cornerFort(LEFT + 6, CY + 8, 2),
      ...leftLaneWall(CY, 12),
      ...bushGrove(CX - 4, TOP + 10, BUSH_PLUS),
      ...coverAlcove(CX - 6, CY - 4, 5, 9, T.WALL, 3),
      ...fenceRow(LEFT + 8, TOP + 16, 8),
      ...waterL(LEFT + 14, TOP + 14, 4, 3),
      ...sandBarrier(CX - 8, CY + 6, 5),
    ],
  ],
  siege: [
    () => [
      ...leftLaneWall(CY - 7, 14),
      ...leftLaneWall(CY + 7, 14),
      ...bushGrove(LEFT + 12, CY, BUSH_RING3),
      ...coverAlcove(LEFT + 8, TOP + 10, 5, 5, T.WALL, 0),
      ...fenceRow(CX - 6, TOP + 8, 6),
      ...cornerFort(LEFT + 6, BOT - 8, 2),
      { kind: "waterRect", x: CX - 2, y: CY - 3, w: 5, h: 7 },
    ],
    () => [
      ...cornerFort(LEFT + 8, TOP + 6, 0),
      ...leftLaneWall(CY - 6, 10),
      ...leftLaneWall(CY + 6, 10),
      ...bushGrove(LEFT + 14, TOP + 14, BUSH_PLUS),
      ...coverAlcove(CX - 6, CY - 5, 8, 11, T.WALL, 2),
      ...sandBarrier(CX - 8, BOT - 12, 6),
      ...fenceRow(LEFT + 10, TOP + 20, 8),
    ],
    () => [
      ...leftLaneWall(CY - 5, 12),
      ...leftLaneWall(CY + 5, 12),
      ...bushGrove(CX - 4, CY, BUSH_BLOCK),
      ...coverAlcove(LEFT + 10, TOP + 8, 5, 5, T.WALL, 1),
      ...waterL(LEFT + 16, BOT - 12, 4, 3),
      ...cornerFort(LEFT + 10, TOP + 8, 0),
      ...sandBarrier(CX - 6, TOP + 14, 8),
    ],
    () => [
      ...crossArena(2, 3),
      ...bushGrove(LEFT + 12, CY, BUSH_BLOCK),
      ...leftLaneWall(CY - 5, 12),
      ...leftLaneWall(CY + 5, 12),
      ...coverAlcove(LEFT + 8, TOP + 8, 6, 6, T.WALL, 0),
      ...fenceRow(CX - 8, TOP + 10, 6),
      ...waterL(LEFT + 12, TOP + 14, 4, 4),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
    ],
    () => [
      ...coverAlcove(LEFT + 8, CY - 5, 8, 11, T.WALL, 2),
      ...bushGrove(CX - 6, CY, BUSH_PLUS),
      ...leftLaneWall(CY, 10),
      ...fenceRow(LEFT + 16, TOP + 10, 6),
      ...waterL(LEFT + 12, TOP + 14, 4, 4),
      ...cornerFort(LEFT + 6, TOP + 6, 0),
      ...sandBarrier(CX - 8, BOT - 10, 6),
    ],
  ],
  bossraid: [
    () => [
      ...leftLaneWall(CY - 6, 12),
      ...leftLaneWall(CY + 6, 12),
      ...coverAlcove(CX - 4, CY - 6, 9, 13, T.WALL, 2),
      ...bushGrove(LEFT + 12, TOP + 10, BUSH_RING3),
      ...fenceRow(LEFT + 10, TOP + 16, 10),
      ...cornerFort(LEFT + 8, BOT - 10, 2),
    ],
    () => [
      ...leftLaneWall(CY, 14),
      ...bushGrove(LEFT + 14, CY - 8, BUSH_PLUS),
      ...bushGrove(LEFT + 14, CY + 8, BUSH_PLUS),
      ...coverAlcove(LEFT + 8, TOP + 10, 5, 5, T.WALL, 0),
      ...sandBarrier(CX - 6, BOT - 12, 8),
      ...waterL(LEFT + 14, TOP + 12, 4, 3),
    ],
    () => [
      ...crossArena(2, 3),
      ...cornerFort(LEFT + 10, TOP + 8, 0),
      ...leftLaneWall(CY - 8, 10),
      ...leftLaneWall(CY + 8, 10),
      ...bushGrove(CX - 4, TOP + 12, BUSH_BLOCK),
      ...coverAlcove(LEFT + 12, CY - 4, 5, 9, T.WALL, 2),
    ],
    () => [
      ...bushGrove(LEFT + 10, TOP + 10, BUSH_RING3),
      ...leftLaneWall(CY - 5, 8),
      ...leftLaneWall(CY + 5, 8),
      ...coverAlcove(CX - 6, CY - 8, 8, 16, T.WALL, 2),
      ...fenceRow(LEFT + 8, TOP + 16, 10),
      ...waterL(LEFT + 16, BOT - 12, 4, 3),
    ],
    () => [
      ...diagonalStairs(LEFT + 8, TOP + 10, 5),
      ...bushGrove(LEFT + 16, CY - 8, BUSH_PLUS),
      ...leftLaneWall(CY - 6, 10),
      ...leftLaneWall(CY + 6, 10),
      ...coverAlcove(LEFT + 10, BOT - 12, 5, 5, T.SAND_WALL, 1),
      ...sandBarrier(CX - 8, TOP + 12, 6),
      ...fenceRow(LEFT + 12, TOP + 20, 8),
    ],
  ],
};
